markdown: kramdown
exclude:
  - LICENSE

layouts_dir: ./_noita
baseurl: /

noita:
  name: PHP 1511 / PHP 2511 Applied Regression Analsis
  description: A first course in Regression!
  author:
    name: Adam J Sullivan
    url: https://vivo.brown.edu/display/asulliv3
    absolute: true
  lang: en
  topbar:
    toggle: Menu
    right:
      - name: Info
        url: /
      - name: Syllabus
        url: /syllabus/
      - name: Calendar
        url: /calendar
      - name: Project
        url: /Project 
      - name: Resources
        url: /resources/
      - name: Links
        url: /links
        absolute: true
      - name: Github
        url: https://github.com/php-1511-2511
        absolute: true
social:
  github: sullivanstatistics
  linkedin: sullivanstats
permalink: /404.html
