markdown: kramdown
exclude:
  - LICENSE

layouts_dir: ./_noita
baseurl: /

noita:
  name: PHP 1510 / PHP 2510 Principles of Biostatistics and Data Analysis
  description: A first course in Statistics and Analysis
  author:
    name: Adam J Sullivan
    url: https://vivo.brown.edu/display/asulliv3
    absolute: true
  lang: en
  topbar:
    toggle: Menu
    right:
      - name: Info
        url: /
      - name: Syllabus
        url: /syllabus/
      - name: Calendar
        url: /calendar
      - name: Resources
        url: /resources/
      - name: Links
        url: /links
        absolute: true
      - name: Github
        url: https://github.com/php-1510-2510
        absolute: true
social:
  github: sullivanstatistics
  linkedin: sullivanstats
permalink: /404.html
