---
title: "Homework 4"
author: "Your Name"
date: "Due: November 26, 2019 at 11:59pm"
output:
  word_document: default
  html_document: default
  pdf_document: default
---


<style type="text/css">
.table {

    width: 80%;
    margin-left:10%; 
    margin-right:10%;
}
</style>

### Homework Policies:

*You are encouraged to discuss problem sets with your fellow students (and with the Course Instructor of course), but you must write your own final answers, in your own words. Solutions prepared ``in committee'' or by copying someone else's paper are not acceptable.  This violates the Brown standards of plagiarism, and you will not have the benefit of having thought about and worked the problem when you take the examinations.*

*All answers must be in complete sentences and all graphs must be properly labeled. *

***Recent homework and exams have been filled with a lot of extra material that is not tables or plots. Please only display the plots and tables and not the code. You may have to look up how to hide the code. In addition, if you display multiple plots, make sure they are all labeled properly and that they are arranged in a grid to keep things more orderly. Points will be deducted for not following these instructions.***

***In this homework you will be required to use .Rmd to do it., you can then knit to a word document of PDF to turn it in.***

***For the PDF Version of this assignment: [PDF](https://raw.githubusercontent.com/php-1510-2510/php-1510-2510.github.io/master/homework/hw4.pdf)***

***For the R Markdown Version of this assignment: [RMarkdown](https://raw.githubusercontent.com/php-1510-2510/php-1510-2510.github.io/master/homework/hw4.Rmd)***

### Turning the Homework in:

*Please turn the homework in through canvas. You may use a pdf, html or word doc file to turn the assignment in.*

[PHP 1510 Assignment Link](https://canvas.brown.edu/courses/1078851/assignments/7748226)

[PHP 2510 Assignment Link](https://canvas.brown.edu/courses/1078852/assignments/7748227)


## Diabetes Data

We have some clinical data from a diabetes study. This is a bit larger than some datasets you have been using in the course so far but more realistic of what you might need. This data comes from [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Diabetes+130-US+hospitals+for+years+1999-2008). I removed some of the columns to make it more manageable. For some uestions below, you will be responsible for filtering out some of the data. 


Make the following into a code chunk so you can read the data in. 
```
load("/path/to/data/diabetes.rda")
```


1. (2 points) How many observations are in this data? 
2. (2 points) How many patients are in this data? 
3. (4 points) What is the highest number of visits for a patient? (Use `dplyr` tools and only print this one patient line.)


When a patient is admitted to a hospital, their admission is generally categorized according to the severity or urgency of their symptoms (e.g., "Elective", "Emergency", etc.). We are interested in the different types of hospital admissions for diabetic patients. We will use the data in the file diabetes data clean.csv to answer several questions related to hospital admissions. Use the appropriate statistical tests, plots, or tables to address the questions below.

4. (10 points) Does it appear that admissions type differs by gender?
    - Display appropriate tables or plots
    - Perform a hypothesis test. 
    - Interpret the results. 

5. (10 points) Consider the hospital admissions of `Elective` and `Emergency` categories. Do males and females differ with respect to these? 
    - Display appropriate tables or plots
    - Perform a hypothesis test. 
    - Interpret the results. 

6. (10 points) We are interested whether patients differ in the number of medications based on whether their admission type was `Elective` or `Emergency`. Using the appropriate statistical test, determine whether or not patients coming in electively or in the case of an emergency tend to receive the same number of medications.


7. (8 points) What are the assumptions of the statistical test we use in 6? Are we confident that these assumptions are satisfied?
    - Use bootstrap confidence intervals and compare them to the hypothesis test and t-distribution confidence intervals in 6. 


## PHP 2510 Only

***Please display your code at the end of this entire question so you may receive partial credit on it.***

8. (15 points) Note that the data in diabetes data clean.csv has patients who had repeat visits to the hospital. We know this to be true because `patient_nbr` is the unique patient identfier, and there are instances of recurrence. 
    We would like to see whether the number of medications changes over time. In particular, for those patients who had 2 (or more) visits, we want to see whether the number of medications tends to be different from the first visit to second visit. Use the appropriate statistical test to investigate this. 
    Note that this problem requires a fair bit of data wrangling to get the data prepared. So consider these hints:
- We can assume encounter id is a variable that uniquely identifies each hospital admission.
- We further assume that encounter IDs are only increasing, so if a given patient has two encounters, the first ID will always be less than the second ID.
- The shape of this data set is typically called "long format"; the patients have repeat measurement recorded as new rows. You will want to get these data in to "wide format". There are good examples you can find by Google-ing.
- Consider using the dplyr package. It's not necessary, but it might help.
- The data reshaping is definitely tricky, don't feel bad if you struggle a bit. It's important to get practice with this, because for many of us, data cleaning and reshaping is a big part of the work we have to do prior to model fitting.